language: ruby
services:
  - redis-server
before_install: gem install bundler -v 1.10.6
install: bundle install -j 4 --retry 3
script:
  - bin/rspec

matrix:
  include:
    - rvm: "2.0.0"
    - rvm: "2.1.7"
    - rvm: "2.2.4"
    - rvm: "2.3.0"
    - rvm: "2.4.0"
