#!/bin/bash -e

command_name=$1
command_args=${@:2}

# we are relying on docker, adding a descriptive name here
# will help when identifiying containers with docker ps
image_name="heartcheck-resque"

# helper to bring container alive
run() {
  args=${@:1}
  docker-compose run --rm -v $PWD:/heartcheck-resque app $args
}

case $command_name in
  setup)
    docker-compose up --build -d
    run bundle install
    ;;
  stop)
    docker-compose down -v --rmi all
    ;;
  bash)
    run bash
    ;;
  bundle)
    run bundle install
    ;;
  console)
    run  bin/console
    ;;
  rspec)
    run bundle exec rspec
    ;;
  usage)
    echo -e "Usage:\n"
    echo -e "heartcheck-resque bash       - access docker sh console"
    echo -e "heartcheck-resque bundle     - runs bundle install"
    echo -e "heartcheck-resque rspec      - runs rspec"
    echo -e "heartcheck-resque setup      - setups docker image"
    echo -e "heartcheck-resque stop       - stops and removes containers, networks and volumes."
    ;;
  *)
    echo -e "\n# Bootstrap Script to dockerize the hearthcheck-resque environment\n"
    $0 usage
  ;;
esac

